@startuml Seguro Fiança

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Usuário", "Pode ser Parceiro ou colaborador")

System_Boundary(c1, "Aplicação Sigafy") {
    Container(sys, "API Aplication", "Laravel", "Provê as funcionalidades do sistema via API")
    ContainerDb(db, "MySQL" ,"DataBase", "Armazena dados, logs, etc")

    System_Boundary(c2, "Containers") {
        Container(seguroFianca,"Seguro Fiança","Módulo")
        
        System_Boundary(c3, "Components") {
            Container(apolice, "Apólice", "Seguro contratado")
        }
    }
}
Rel_L(user, sys, "Acessa a plataforma")
Rel(sys, seguroFianca, " Interage com os módulos","HTTPS")
Rel(seguroFianca, apolice, " No final do dia emite uma apólice")
Rel_U(seguroFianca, db, " Faz requisições","sync: TCP")
@enduml
